### ISSUE TITLE
next steps on SequenceCollection and Alignment objects

### ISSUE THREAD

**Issue by gregcaporaso** [biocore/scikit-bio#194]
Done
-------
- [x] what happens if multiple `BiologicalSequences` with the same `identifier` (fixed: this is explicitly disallowed now)

Merged (#220)
-------------------------------------
- [x] write ``__str__``
- [x] **BUG**: the `positional_entropies` calculation should perform special handling of gap characters - the plan will be to pass in a function which takes positional frequencies when there is a gap present, and returns the entropy value. This will default to returning `nan`. This should likely be the case for degenerate characters as well.
- [x] add deprecation warning to ``toFasta`` in favor of ``to_fasta``, which is what it calls now (``toFasta`` is currently necessary as some code, eg PyNAST, expects cogent SequenceCollection objects, which implements this method) 
- [x] write ``_contains__``
- [x] write ``__reversed__``
- [x] simplify example output for ``SequenceCollection.degap()`` (see comment in #195). 

Still to do
------------

- [x] allow other distance metrics to be computed by Alignment.distance (related to creating a SequenceCollection.distance method) 
- [ ] implement subset functionality for ``SequenceCollection`` which takes `seqs_to_keep`
- [x] write SequenceCollection.distance, which by default returns kmer distances between sequences (see #25, which includes computing the kmers for a sequence)
- [x] rename ``from_fasta_records`` to ``from_tuples``, as there is no format-specificity at this stage
- [x] write ``to_tuples`` method, which takes a constructor (e.g., ``str`` or ``None``) and returns tuples of (identifier, sequence) pairs, where the constructor is called on each sequence
- [x] refactor ``sequence_frequencies`` to call ``BiologicalSequence.k_word_frequencies(k=1)`` (add ``k=1`` as default, but allow other values of k to be passed through for easy computing of all k-word frequency vectors), in #264

Ported from #26 
--------------------------
- [x] write SequenceCollection.distance, which by default returns kmer distances between sequences
- [x] implement subset functionality for ``SequenceCollection`` which takes `seqs_to_keep`

**Comment by ebolyen** [comment]
closing in favor of #823
