### ISSUE TITLE
checklist.py improvements

### ISSUE THREAD

**Issue by jairideout** [biocore/scikit-bio#461]
Now that powertrip.py is merged, it'd be great to add some more advanced sanity checks (the first item is pulled from the original issue #446):

- [x] every file has the same header (e.g., copyright info, future imports, etc.)
- [ ] `MANIFEST.in` references files/dirs that exist
    - this is one of the most error-prone parts of the release process and has thwarted us previously
- [x] Cython/generated C code timestamp checking

Any other sanity checks to add?

**Comment by gregcaporaso** [comment]
It would be useful to add checks for decorator order and presence/absence to checklist.py. These are going to be easy to mess up.

**Comment by jairideout** [comment]
:+1:

**Comment by jairideout** [comment]
@gregcaporaso I created #1033 to track your latest request re: decorators. I'd like to close this "wishlist" issue once #1032 is merged (all of the other features in this issue are finished).
