### ISSUE TITLE
Refactor Alignment

### ISSUE THREAD

**Issue by ebolyen** [biocore/scikit-bio#823]
`A user interacts with an alignment using a simple axis-based API, and easily aligns sequences.`

- [ ] Substitution matrix (#161)
- [ ] Convenience method for pairwise alignment (#474)
- [ ] Integrate SSW more cleanly into alignment algorithms (#534)
- [ ] sane sequence filtering (#815)

past discussion available at (#194)
