### ISSUE TITLE
Refactor Sequence Objects

### ISSUE THREAD

**Issue by ebolyen** [biocore/scikit-bio#826]
`Sequence objects should be fast, and the API should include arbitrary translation as well as being simple and easy to recall.`

- [x] Improved complement performance (#412)
- [x] Use numpy array internally (#60, #556)
- [ ] Integrate genetic code (#337)
- [ ] Central dogma should be evident in the methods of these objects. (partially #744)
- [x] Length checking in distance method (#514)
- [ ] improve k_words API (#669)
- [x] `fraction_same` bug (#888)
